# Generated by Django 4.2.8 on 2024-06-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencevalue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='values',
        ),
        migrations.AddField(
            model_name='preference',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PreferenceCategory',
        ),
        migrations.DeleteModel(
            name='PreferenceValue',
        ),
    ]
