# Generated by Django 4.2.8 on 2024-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preference',
        ),
    ]
